name: Build Tauri application
on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your branch name if different
    paths:
      - 'Dockerfile.centos79'
      # - 'Dockerfile.centos79.use'

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
    #  - name: Checkout code
    #    uses: actions/checkout@v2
    #    with:
    #      fetch-depth: 2  # Fetch the last 2 commits to compare changes

      # - name: Check for Dockerfile changes
      #   id: check_changes
      #   run: |
      #     git fetch origin main
      #     DOCKERFILE1_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -q "Dockerfile.centos79") # && echo "true" || echo "false"
      #     DOCKERFILE2_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -q "Dockerfile.centos79.use" ) #&& echo "true" || echo "false"
          
      #     echo "dockerfile1_changed=$DOCKERFILE1_CHANGED" >> $GITHUB_OUTPUT
      #     echo "dockerfile2_changed=$DOCKERFILE2_CHANGED" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        # if: steps.check_changes.outputs.dockerfile1_changed == 'true' || steps.check_changes.outputs.dockerfile2_changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image for centos79
        # if: steps.check_changes.outputs.dockerfile1_changed == 'true'
        run: |
          IMAGE_TAG="mostuf25562/tauri"
          docker build -f Dockerfile.centos79 -t $IMAGE_TAG .
          echo "Built image $IMAGE_TAG"
          docker push $IMAGE_TAG

      # - name: Build and Push Docker image for centos79.use
      #   if: |
      #     steps.check_changes.outputs.dockerfile2_changed == 'true' || 
      #     steps.check_changes.outputs.dockerfile1_changed == 'true'
      #   run: |
      #     IMAGE_TAG_USE="mostuf25562/tauri.use:2"
      #     docker build -f Dockerfile.centos79.use -t $IMAGE_TAG_USE .
      #     echo "Built image $IMAGE_TAG_USE"
      #     docker push $IMAGE_TAG_USE
