
# name: Build Raspberry Pi App and Docker Image

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main  # Change this to your branch name if different

# jobs:
#   docker_build_and_push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ vars.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         run: docker build -f Dockerfile.ubuntu1804_2 -t mostuf25562/tauri:1 .

#       - name: Push Docker image
#         run: docker push mostuf25562/tauri:1

#       # - name: Build Docker image
#       #   run: docker build -f Dockerfile.centos79.use -t mostuf25562/tauri:2 .

#       # - name: Push Docker image
#       #   run: docker push mostuf25562/tauri:2
        
#       - name: test image
#         run: docker run mostuf25562/tauri:1 ldd --version
